src/Entity/Selfie.php
<?php

namespace App\Entity;

use App\Repository\SelfieRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SelfieRepository::class)
 */
class Selfie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $commentary;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name_person;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getCommentary(): ?string
    {
        return $this->commentary;
    }

    public function setCommentary(?string $commentary): self
    {
        $this->commentary = $commentary;

        return $this;
    }

    public function getNamePerson(): ?string
    {
        return $this->name_person;
    }

    public function setNamePerson(?string $name_person): self
    {
        $this->name_person = $name_person;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Beam Me Up Coffee{% endblock %}</title>
    {% block favicon %}
        <link rel="apple-touch-icon" sizes="57x57" href="{{ asset('IMG/favicon.ico/apple-icon-57x57.png') }}">
        <link rel="apple-touch-icon" sizes="60x60" href="{{ asset('IMG/favicon.ico/apple-icon-60x60.png') }}">
        <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('IMG/favicon.ico/apple-icon-72x72.png') }}">
        <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('IMG/favicon.ico/apple-icon-76x76.png') }}">
        <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('IMG/favicon.ico/apple-icon-114x114.png') }}">
        <link rel="apple-touch-icon" sizes="120x120" href="{{ asset('IMG/favicon.ico/apple-icon-120x120.png') }}">
        <link rel="apple-touch-icon" sizes="144x144" href="{{ asset('IMG/favicon.ico/apple-icon-144x144.png') }}">
        <link rel="apple-touch-icon" sizes="152x152" href="{{ asset('IMG/favicon.ico/apple-icon-152x152.png') }}">
        <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('IMG/favicon.ico/apple-icon-152x152.png') }}">
        <link rel="icon" type="image/png" sizes="192x192"
              href="{{ asset('IMG/favicon.ico/android-icon-192x192.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('IMG/favicon.ico/favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="96x96" href="{{ asset('IMG/favicon.ico/favicon-96x96.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('IMG/favicon.ico/favicon-16x16.png') }}">
        <link rel="manifest" href="{{ asset('IMG/favicon.ico/manifest.json') }}">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="{{ asset('IMG/favicon.ico/ms-icon-144x144.png') }}">
        <meta name="theme-color" content="#ffffff">
    {% endblock %}
    {% block stylesheets %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('CSS/Main.css') }}">
    {% endblock %}
</head>
<body>
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-light mbg">
        <a class="navbar-brand" href="{{ path('index') }}">
            <img src="{{ asset('/IMG/logo.png') }}" width="60" height="60" alt="Beam Me Up Coffee" loading="lazy">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link navclr" href="{{ path('index') }}">Homepage <span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navclr" href="{{ path('guestbook') }}">Guestbook</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navclr" href="{{ path('impression') }}">Impression</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link navclr" href="{{ path('view_selfie') }}">Selfies from customers</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link navclr" href="{{ path('contact_location') }}">Contact/Locations</a>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}
{% block container %}
<div class="container" style="margin-bottom: 100px">
    {% endblock %}
    {% block body %}



    {% endblock %}
</div>
{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
{% endblock %}
{% block footer %}
    <footer class="footer mbg">
            <span>
                <p class="pt-3">&copy;{{ "now"|date('Y') }} Beam Me Up Coffee</p>
            </span>
    </footer>
{% endblock footer %}
</body>
</html>

templates/contactLocation.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1 class="mt-4" style=" text-align: center">Contact/Locations</h1>
    <div class="mbg center mx-auto mt-3 mb-5 text-justify w-50 ">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d116389.72807736036!2d-106.1423993088043!3d32.772801951398336!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e06118c1d2ecb5%3A0x561cbf6364fcf414!2sTularosa%2C%20New%20Mexico%2088352%2C%20Verenigde%20Staten!5e1!3m2!1snl!2snl!4v1590586232782!5m2!1snl!2snl"  height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0" class="w-100"></iframe>
        <ul class="p-2" style="list-style-type: none;">
            <li>Beam Me Up Coffee White Sands National Park Plc. </li>
            <li>12 Dunes Drive</li>
            <li>White Sands NM</li>
            <li>88002</li>
            <li><br></li>
            <li><b>mail</b>:<a class="lnk ml-2 navclr" href="mailto:info@bmuc.white-sands.com">info@bmuc.white-sands.com</a></li>
            <li><b>tel</b>: <a class="lnk ml-3 navclr" href="tel:001 505 9012021">001 505 9012021</a></li>
        </ul>
    </div>
{% endblock %}

templates/guestbook.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1 class="mt-4" style=" text-align: center">Guestbook</h1>
    {% for guest in guests %}
        <div class="mbg center mx-auto mt-3 mb-5 text-justify w-50 p-2 ">
            <p class="mw-1" style="overflow: auto">
        {{ guest.commentary }}
            </p>
        </div>
    {% endfor %}
    <div class="mbg center mx-auto mt-5 mb-5 text-justify w-50 p-2 ">
        <form method="post" name="guestbook">
            <textarea name="comment" class="w-100 mh-25 " required></textarea>
            <br>
            <input class="btn btn-light" style="border-color: #0a0a0a" type="submit" name="submit">
        </form>

    </div>
{% endblock %}

templates/impression.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="mbg center mx-auto mt-5 mb-5 text-justify w-50 ">
        <div id="carouselExampleFade" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner ">
                <div class="carousel-item active">
                    <img src="{{ asset('IMG/trinity.jpg') }}" class="d-block slider mh-100 mw-100" alt="trinity">
                    <h2 style=" text-align: center">The place of the manhattan project</h2>
                    <p style=" padding: 2em ">
                        our Coffeehouses is close ad the Trintity Test Site the place of the nuclear age, can
                         visits  the site on the first Saturdays of April and October.
                        The rest of the year the site is closed to the public because it lies within the impact zone for missiles fired into the northern part of WSMR.
                    </p>
                </div>
                <div class="carousel-item">
                    <img src="{{ asset('IMG/coffee4.jpg') }}" class="d-block slider mh-100 mw-100" alt="Coffee">
                    <h2 style=" text-align: center">The best coffee</h2>
                    <p style=" padding: 2em ">
                        We serve it fresh and cool, in a way that you’ll never know that it has been roasted.
                        We believe people should be able to enjoy coffee wherever they are.
                        We are here to share our passion for coffee, and to offer high-quality coffee, with the world. We are here to help you enjoy your coffee.
                    </p>
                </div>
                <div class="carousel-item">
                    <img src="{{ asset('IMG/whitesands.jpg') }}" class="d-block slider mh-100 mw-100" alt="sands">
                    <h2 style=" text-align: center">Seeing Unique Animals</h2>
                    <p style=" padding: 2em ">
                        Rising from the heart of the Tularosa Basin is one of the world's great natural wonders - the glistening white sands of New Mexico.
                        Great wave-like dunes of gypsum sand have engulfed 275 square miles of desert, creating the world's largest gypsum dunefield.
                        White Sands National Park preserves a major portion of this unique dunefield, along with the plants and animals that live here.
                    </p>
                </div>
                </div>
            </div>
        </div>


{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="mbg center mx-auto mt-5 mb-5 text-justify w-50 ">
    <div id="carouselExampleFade" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner ">
            <div class="carousel-item active">
                <img src="{{ asset('IMG/house.jpg') }}" class="d-block slider mh-100 mw-100" alt="house">
            </div>b
            <div class="carousel-item">
                <img src="{{ asset('IMG/exrt.jpg') }}" class="d-block slider mh-100 mw-100" alt="exrt">
            </div>
            <div class="carousel-item">
                <img src="{{ asset('IMG/coffee2.jpg') }}" class="d-block slider mh-100 mw-100" alt="coffee">
            </div>
        </div>
    </div>
    <h2 style=" text-align: center">Welcome</h2>
    <p style=" padding: 2em ">
    We serve only the best coffee from around the world. Our coffee is carefully selected and carefully roasted by experienced baristas.
    We offer a range of services to suit the needs of every particular coffee-lovers. We serve delicious coffee in our own traditional way,
    and we care about the quality of the product we source and prepare.
    Our focus is on providing the most delicious and relaxing way to enjoy coffee with views of White Sands National Park.
    </p>
    </div>
{% endblock %}

templates/selfieview.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <h1 class="mt-4" style=" text-align: center">Selfies from customers</h1>
    {% for selfie in selfies %}
        <div class="center mx-auto mt-3 text-justify w-50 ">
            <div class="border border-warning">
            <img src="{{ asset( selfie.photo) }}" class=" mx-auto w-100 d-block img-fluid">
            </div>
            <div class="mbg p-1">
            <p>
                {{ selfie.commentary }}

            </p>
            <p style="text-align: right;" class="mb-0">
            {{ selfie.namePerson }}
            </p>
        </div>
            {% if app.user is not null %}
            <div style="text-align: right">
                {{ include('selfie/_delete_form.html.twig') }}
            </div>
            {% endif %}
        </div>
    {% endfor %}

    <div class="center mx-auto mt-5 mb-5 text-justify w-25 p-2 ">
        <a class="btn btn-light w-100" style="border-color: #0a0a0a" href="{{ path('selfie_new') }}">Upload Selfie</a>
    </div>
{% endblock %}